// Accounts
export const FETCH_ACCOUNTS = 'FETCH_ACCOUNTS';
export const FETCH_ACCOUNTS_STATUS = 'FETCH_ACCOUNTS_STATUS';

// Auth
export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';

// Cards
export const FETCH_CARDS = 'FETCH_CARDS';
export const FETCH_CARDS_STATUS = 'FETCH_CARDS_STATUS';
export const CARD_CHANGE_PIN = 'CARD_CHANGE_PIN';
export const CARD_CHANGE_LIMITS = 'CARD_CHANGE_LIMITS';

// Messages
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const FETCH_MESSAGES_STATUS = 'FETCH_MESSAGES_STATUS';
export const MESSAGE_TOGGLE = 'MESSAGE_TOGGLE';
export const MESSAGE_REMOVE = 'MESSAGE_REMOVE';
export const FETCH_MESSAGES_PAGINATION_STATUS = 'FETCH_MESSAGES_PAGINATION_STATUS';
export const SET_MESSAGES_PAGE = 'SET_MESSAGES_PAGE';

// Profile
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_STATUS = 'FETCH_PROFILE_STATUS';
export const USER_CHANGE_DETAILS = 'USER_CHANGE_DETAILS';

// Transactions
export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS';
export const FETCH_TRANSACTIONS_STATUS = 'FETCH_TRANSACTIONS_STATUS';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const FETCH_TRANSACTIONS_PAGINATION_STATUS = 'FETCH_TRANSACTIONS_PAGINATION_STATUS';
export const SET_TRANSACTIONS_PAGE = 'SET_TRANSACTIONS_PAGE';

// Modal
export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

// Panel
export const FETCH_INITIAL_DATA = 'FETCH_INITIAL_DATA';
export const FETCH_INITIAL_DATA_STATUS = 'FETCH_INITIAL_DATA_STATUS';
